# Generated by Django 3.2 on 2021-11-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30, unique=True)),
                ('spwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64)),
                ('raw_name', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
